# Generated by Django 3.2.14 on 2022-07-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeclock',
            name='hours',
            field=models.IntegerField(default=0),
        ),
    ]
